"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import MainNavbar from "@/components/mainNavbar";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Velocify UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <body className={inter.className}>
        <div className="z-10 fixed w-screen ">
          <MainNavbar />
        </div>
        <ScrollToTopButton />
        <div className="z-0  ">{children}</div>
      </body>
    </html>
  );
}
